#!/usr/bin/env php
<?php

use Symfony\Bundle\WebServerBundle\Command\ServerLogCommand;
use Symfony\Bundle\WebServerBundle\Command\ServerRunCommand;
use Symfony\Bundle\WebServerBundle\Command\ServerStartCommand;
use Symfony\Bundle\WebServerBundle\Command\ServerStatusCommand;
use Symfony\Bundle\WebServerBundle\Command\ServerStopCommand;
use Symfony\Component\Console\Application;

set_time_limit(0);

require __DIR__ . '/vendor/autoload.php';

$app = new Application;

$root = getenv('PHP_DOCROOT') ?: __DIR__ . '/public';
$env = getenv('PHP_ENVIRONMENT') ?: 'dev';

$app->add(new ServerLogCommand);
$app->add(new ServerRunCommand($root, $env));
$app->add(new ServerStartCommand($root, $env));
$app->add(new ServerStatusCommand);
$app->add(new ServerStopCommand);

$app->run();
